# here is the base image
FROM ubuntu:14.04
MAINTAINER  nawfalrezo@gmail.com
# get all the updates
RUN apt-get update -y
# install the essential requirements
RUN apt-get install -y curl wget git build-essential
# add a label
LABEL version="1.0"